services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/web:/var/www/html
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      # args:
      #   WP_DB_NAME: ${WP_DB_NAME}
      #   WP_DB_USER: ${WP_DB_USER}
      #   WP_DB_USER_PASS: ${WP_DB_USER_PASS}
      #   WP_ADMIN_USER: ${WP_ADMIN_USER}
      #   WP_ADMIN_PASS: ${WP_ADMIN_PASS}
    volumes:
      - ./volumes/web:/var/www/html
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_USER_PASS: ${WP_DB_USER_PASS}
    env_file:
      - .env
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
