services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - default
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - web_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - default
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_USER_PASS: ${WP_DB_USER_PASS}
    env_file:
      - .env
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    networks:
      - default
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

networks:
  default:

volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pgrossma/data/web
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pgrossma/data/mysql
      o: bind