services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    ports:
      - "8080:80"
